services:
  database-codeforces:
    image: postgres
    container_name: database-codeforces
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 10s
      retries: 10

  redis-codeforces:
    image: redis
    container_name: redis-codeforces
    restart: always
    ports:
      - '6370:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 10s
      retries: 10

  backend:
    image: ghcr.io/nagmani001/codeforces/backend:latest
    container_name: backend-codeforces
    restart: always
    ports:
      - "4001:4001"
    env_file:
      - .env.backend
    depends_on:
      database-codeforces:
        condition: service_healthy
      redis-codeforces:
        condition: service_healthy

  worker:
    image: ghcr.io/nagmani001/codeforces/worker:latest
    container_name: worker-codeforces
    restart: always
    env_file:
      - .env.worker
    depends_on:
      redis-codeforces:
        condition: service_healthy

  web:
    image: ghcr.io/nagmani001/codeforces/web:latest
    container_name: web-codeforces
    restart: always
    ports:
      - "4000:4000"

volumes:
  pgdata:
